import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { MantineProvider } from "@mantine/core";

import '@mantine/core/styles.css';
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Company Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <Navbar />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
